version: "3.9"

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 63306:3306 # Expose port to make db directly accessable
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - wttt-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 63080:80
    env_file: .env
    networks:
      - wttt-network
    depends_on:
      - db

volumes:
  db:
  db-admin:


networks:
  wttt-network:
    driver: bridge
