version: "3.9"

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - wttt-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    env_file: .env
    networks:
      - wttt-network
    depends_on:
      - db
    # server:
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   image: wttt-33/server
    #   container_name: wttt-33_server
    #   restart: always
    #   env_file: .env
    #   # environment:
    #   #   - NODE_ENV=development
    #   ports:
    #     - "63000:1234"
    #   volumes:
    #     - .:/home/node/app
    #   # networks:
    #   #   - wttt-network
    #   depends_on:
    #     - db
    # yarn:
    #   image: node:18.10.0-alpine3.16
    #   working_dir: /home/node/app
    #   profiles: ["cli"]
    #   volumes:
    #     - ../.yarn-cache:/yarn-cache:rw
    #     - .:/home/node/app
    #   entrypoint: ["yarn"]
    #   environment:
    #     YARN_CACHE_FOLDER: "/yarn-cache"

volumes:
  db:
  db-admin:


networks:
  wttt-network:
    driver: bridge
